### ISSUE TITLE
Not-quite-ISO timestamps

### ISSUE THREAD

**Issue by sjpfenninger** [xray/xray#316]
I have trouble reading NetCDF files obtained from MERRA. It turns out that their time unit is of the form "hours since 1982-1-10 0". Because there is only a single "0" for the hour, rather than "00", this is not an ISO compliant datetime string and ``pandas.Timestamp`` raises an error (see pydata/pandas#9434).

This makes it impossible to open such files unless passing ``decode_times=False`` to ``open_dataset()``.

I wonder if this is a rare edge case or if xray could attempt to intelligently handle it somewhere (maybe in ``conventions._unpack_netcdf_time_units``). For now, I just used NCO to append an extra 0 to the time unit (luckily all files are the same, so I can just do this across the board): ``ncatted -O -a units,time,a,c,"0" file.nc``

**Comment by shoyer** [comment]
What a hassle! Unfortunately my experience has been that non-ISO conformant time units are not uncommon. I'll take a look into this.

We did add one fix to improve the time unit parsing since the last release. You might want to try installing the dev version off github to see if it fixes your issue. Otherwise you can also do the sort of fixup you describe by loading the dataset with decode_cf=False, fixing the metadata and then calling xray.decode_cf.

**Comment by shoyer** [comment]
It looks like `netcdftime` (part of the `netCDF4` package) can parse this string correctly, so we should probably fall back to using that:
```
In [26]: netcdftime.num2date(0, 'hours since 1981-1-10 0')
Out[26]: datetime.datetime(1981, 1, 10, 0, 0)
```

The other possibility is adding a `datetime_format` argument to `open_dataset`.

**Comment by sjpfenninger** [comment]
I think falling back to `netcdftime` would be preferrable to a `datetime_format` argument since it would just automagically work (although a `datetime_format` could be useful for other, trickier netCDF files). I could have a go at doing this later in the week and submit a PR, if it's helpful.

**Comment by shoyer** [comment]
Yes, if you want to give it a shot, that would be great!

The only thing to watch out for is that `netCDF4`/`netcdftime` is an optional dependency, so you need to ensure that test methods are properly decorated with `requires_netCDF4`; otherwise the CI tests will fail. I'm not too concerned about being able to decode datetime units without netCDF4 installed, though I suppose that would be nice to maintain if possible (just import netcdftime locally when the fallback is used).

**Comment by sjpfenninger** [comment]
I noticed that you already have a fallback option and I simply made use of that, which solves this problem in a way that looks reasonable to me.

However, I'm still not quite happy with the way errors were/are handled: before this change, reading a file with the non-standard datetime format would work without errors, but trying to do anything with the dataset after opening it would produce a ValueError, which from an end-user perspective doesn't help much to figure out where the error is coming from.

I suppose with the change in my PR, for cases where python-netCDF4 is not installed, one would instead get an ImportError without explanation (one wouldn't know why we tried to import the optional dependency). Maybe something like a wrapper to import netCDF4 which raises a context-specific ImportError message would be useful?

**Comment by shoyer** [comment]
I agree, this is not ideal. We really should try to decode time units at the time a dataset is opened, not just when the values are read (which open leads to a failed `repr()`). Adding some sort of more helpful error message to catch exception that arise would also help (e.g., "cannot read non-ISO time units: netCDF4 not installed").

**Comment by shoyer** [comment]
Made a new issue for datetime decoding error handling: #323
