### ISSUE TITLE
"loosing" virtual variables

### ISSUE THREAD

**Issue by mathause** [xray/xray#386]
Once I take a mean over virtual variables, they are not available any more. 

    import pandas as pd
    import numpy as np
    import xray
    t = pd.date_range('2000-01-01', '2000-12-31', freq='6H')
    x = np.random.rand(*t.shape)
    time = xray.DataArray(t, name='t', dims='time')
    ts = xray.Dataset({'x' : ('time', x), 'time' : time})
    ts_mean = ts.groupby('time.date').mean()
    ts_mean.virtual_variables

Is this intended behaviour? And could I get them back somehow?

**Comment by mathause** [comment]
Ok the problem seems to be that the datetime64 array is converted to an object array.

    print(ts)
    print(ts_mean)

Could you keep it as a datetime64 object? Or would that be a pandas problem?

**Comment by shoyer** [comment]
The better solution here is to use `resample` rather than `groupby('time.date')`:
```
ts_mean = ts.resample('1D', dim='time')
```

`time.date` and `time.time` (with is currently broken) are weird virtual variables, because, like you point out, they create object arrays. That makes them not so useful. It might be better to get rid of them entirely, or to replace them with some sort of shortcut that returns datetime64 instead.

**Comment by mathause** [comment]
Thanks, it works. I didn't think of this.

However, for anything else than the mean this would not work? So I would opt for the second option.

**Comment by shoyer** [comment]
Resampling actually supports custom aggregation methods with the `how` parameter: http://xray.readthedocs.org/en/stable/generated/xray.Dataset.resample.html#xray.Dataset.resample
