### ISSUE TITLE
NetCDF attributes like `long_name` and `units` lost on `.mean()`

### ISSUE THREAD

**Issue by j08lue** [xray/xray#442]
When reading in a variable from netCDF, the standard attributes like `long_name`, `standard_name`, and `units` are being propagated, but apparently lost when calling ~~`.load()`~~ `.mean()` on the `DataArray`.

Couldn't these CF-[Highly Recommended Variable Attributes](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery#Highly_Recommended_Variable_Attributes) be kept during this operation?

(What to do with them afterwards, e.g. upon merge, is a different question, [unresolved also in the pandas community](https://github.com/pydata/pandas/issues/2485).)

EDIT: the problem actually occurs when calling `.mean()` (not `.load()`, as originally posted).

**Comment by shoyer** [comment]
Hmm. This is definitely a bug -- load should preserve all metadata.

**Comment by shoyer** [comment]
Could you post an example dataset/code for which this occurs? I'm struggling to reproduce this.

**Comment by j08lue** [comment]
Sorry for the confusion, the loss of attributes actually occurs when applying `.mean()` (rather than `.load()`). 

See this [notebook](https://gist.github.com/j08lue/c4a6b4bd504c0a7598b2) (same in [nbviewer](http://nbviewer.ipython.org/gist/j08lue/c4a6b4bd504c0a7598b2)) for an example with some opendap-hosted data.

**Comment by shoyer** [comment]
Ah. So this is intentional. `.mean()` does have an optional parameter that lets you control this -- try `.mean(keep_attrs=True)`.

The basic problem is that it's ambiguous how to handle attributes like units after doing computation. I don't want to inspect attributes and choose some to preserve and others to remove, so we have a choice of either preserving all attributes in an operation or removing all of them.

Obviously, for some aggregations (e.g., `sum` or `var`) it doesn't make sense to preserve attributes (which commonly include units). I suppose we could make an exception for aggregations like mean/median/std, but it's also weird to have some aggregations that preserve attributes and others that don't.

**Comment by j08lue** [comment]
That makes sense. Great that there is an option to `keep_attrs`. Closing this issue.
