### ISSUE TITLE
add diff method to DataArray class

### ISSUE THREAD

**Issue by andreas-h** [xray/xray#490]
I think it would be useful if the `DataArray` class had a `diff` method, equivalent to the `pandas.DataFrame.diff` method.

**Comment by andreas-h** [comment]
If you can give me a pointer where in the code this would have to be implemented, I could give it a try myself ...

**Comment by shoyer** [comment]
I agree, this would be useful. Probably should take a `dim` argument that specifies the dimension along which to take the differences.

I guess `x.diff('x')` would do something like the following?
```python
In [28]: x = xray.Dataset({'foo': ('x', [5, 5, 6, 6])})

In [29]: start = x.isel(x=slice(None, -1))

In [30]: end = x.isel(x=slice(1, None))

In [31]: start.coords['x'] = end.coords['x']

In [32]: end - start
Out[32]:
<xray.Dataset>
Dimensions:  (x: 3)
Coordinates:
  * x        (x) int64 1 2 3
Data variables:
    foo      (x) int64 0 1 0
```

Since this logic is the same for Dataset and DataArray objects, it could live as a method on `BaseDataObject` in `xray/core/common.py`: https://github.com/xray/xray/blob/v0.5.2/xray/core/common.py#L147

If you find yourself needing to write dataset or dataarray specific logic, write it as a Dataset method and follow the example of DataArray.swap to extend it to dataarrays: https://github.com/xray/xray/blob/v0.5.2/xray/core/dataarray.py#L659
