### ISSUE TITLE
issue with xray.open_mfdataset and binary operations

### ISSUE THREAD

**Issue by razvanc87** [xray/xray#542]
example:

```python
with xray.open_mfdataset(...) as ds:
    a = ds['x'] * ds['y']
```

gives:

`NotImplementedError: Dask.array operations only work on dask arrays, not numpy arrays.` If I do `ds.load()` first then all is good... I guess this is an `xray` issue, not `dask`.

**Comment by shoyer** [comment]
So the issue here is that xray needs to load some arrays into memory as numpy arrays (e.g., to do indexing), but dask arrays don't know how to interact with numpy arrays:
https://github.com/blaze/dask/issues/290

You can work around this by manually rechunking:
```python
with xray.open_mfdataset(...) as ds:
    ds = ds.chunk()
    a = ds['x'] * ds['y']
```

Kind of awkward but it works for now.

**Comment by razvanc87** [comment]
I see, I'll try that, thanks

**Comment by razvanc87** [comment]
Nope, it gives me the same error. It seem to only work with `ds.load()`.

**Comment by shoyer** [comment]
Just fixed this issue on the dask side: https://github.com/blaze/dask/pull/622

**Comment by razvanc87** [comment]
cool, thanks
