### ISSUE TITLE
Tabular Data Packages and xray

### ISSUE THREAD

**Issue by rgrp** [xray/xray#587]
Hi, after speaking with someone today re Tabular Data Packages and NetCDF I wanted to flag Tabular Data Packages:

http://data.okfn.org/doc/tabular-data-package

Clearly, NetCDF is clearly its own dedicated format. However, I see that NetCDF has several conversions / integrations to tabular style structures. Moreover, the purpose of xray is to give a pandas-oriented wrapper to NetCDF and pandas now has tabular data package support - see https://github.com/pydata/pandas-datareader/issues/80

In this context Tabular Data Packages could be both a useful intermediate data structure and additionally supported input or output format.

**Comment by shoyer** [comment]
In what contexts would it make sense for xray to directly read and write these formats? We have first class support for reading/writing pandas data frames, which generally seems like a much better fit for generic tabular data.

If tabular data packages has direct support for multi-dimensional arrays then this could make sense. Otherwise, users probably should be explicitly converting to and from tabular formats.

**Comment by rgrp** [comment]
Where do you pull data from externally - or is it always pandas data frames? If you pull from external formats my question would be whether you cuold support pulling in tabular data packages ...

**Comment by shoyer** [comment]
To map unambiguously to the xray data model, an external dataset needs to be explicitly labeled with axis names and tick labels. Pandas dataframes, for example, only make sense because they are explicitly labeled by an index (row labels).

As far as I can tell, tabular data packages does not describe data with such labels, but rather does generic tabular data. That's great, but xray is a not a tool for generic tabular data (it requires more structure), and importing this data through our interface to pandas provides a clean way to indicate this structure

**Comment by shoyer** [comment]
To answer your last question, xray natively supports IO from netCDF/HDF5 and OpenDAP. We leave CSV parsing to pandas.

**Comment by femtotrader** [comment]
This might help https://github.com/xray/xray/issues/607
