### ISSUE TITLE
roll method

### ISSUE THREAD

**Issue by rabernat** [xray/xray#624]
I would like to pick up my idea to add a roll method. Among many uses, it could help with #623. 

The method is pretty simple.

```python
def roll(darr, n, dim):
    """Clone of numpy.roll for xray objects."""
    left = darr.isel(**{dim: slice(None, -n)})
    right = darr.isel(**{dim: slice(-n, None)})
    return xray.concat([right, left], dim=dim, data_vars='minimal',
    				   coords='minimal')
```

I have already been using this function a lot (defined from outside xray) and find it quite useful. I would like to create a PR to add it, but I am having a little trouble understanding how to correctly "inject" it into the api. A few words of advice from @shoyer would probably save me a lot of trial and error.

**Comment by shoyer** [comment]
`Dataset` and `DataArray` both inherit from `BaseDataObject`, so that would be an appropriate place to add this method:
https://github.com/xray/xray/blob/5abc994798fb773d965adccf0dd8d932357044e0/xray/core/common.py#L148

For the API design, I wonder if it would be better to use `ds.roll(time=100)` instead of `ds.roll(100, 'time')`. Thoughts?

**Comment by darothen** [comment]
Using an API like `ds.roll(time=100)` would be more consistent with other aggregation/manipulation routines, and there's nothing in @rabernat 's code that forbids that call signature.

**Comment by shoyer** [comment]
I agree that `ds.roll(time=100)` seems like the more consistent syntax.

`shift` seems like the natural companion method to `roll`. It should work the same way, but insert NaNs instead of other of the arrays. No need to add shift in this PR, of course, but it's a natural follow up.

Does it makes sense to roll in integer or coordinate space? e.g., should we be able to write `ds.roll(longitude=180)` regardless of the actual spatial resolution? I'm thinking it's probably better to stick with integers, simply because coordinates are not necessarily evenly spaced.

**Comment by darothen** [comment]
Is there another easy way to add a constant offset to all the values of a dimension (e.g. add, say, 10 meters to every value in the dimension)? I don't typically use operations like that, but I can see where they might be useful.

If not, then rolling in integer space is the way to go.

**Comment by rabernat** [comment]
Thanks for the advice. I'll give it a shot.

I think I will just do integer rolls for now.

Non-integer rolls or coordinate rolls are essentially interpolation. That would be something useful to have as well. But let's start small.

**Comment by shoyer** [comment]
I have a PR adding `shift` up for review in #666. I think `roll` could be implemented pretty similarly.

**Comment by rabernat** [comment]
Thanks for the tip! I have obviously not worked on this. Just had my last lecture of the semester today though, so maybe something will happen soon!

**Comment by shoyer** [comment]
see #666 for an implementation of roll, as well
